In [1]:
import pandas as pd

In [2]:
info ={
    "name" : ["aayusi" , "shilpi" , "anjali" , "kb"],
    "cgpa" : [9.5 , 7.5 , 5.6 ,7.8]
}

df = pd.DataFrame(info)
print(df)

     name  cgpa
0  aayusi   9.5
1  shilpi   7.5
2  anjali   5.6
3      kb   7.8

In [3]:
df

     name  cgpa
0  aayusi   9.5
1  shilpi   7.5
2  anjali   5.6
3      kb   7.8

In [8]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#index
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
3

In [16]:
s = pd.Series([21,23,22,34], index= ["alice" , "bob" , "chrlic" , "dennies"])
print(s)

print(s["bob"])
print(s.index)

alice      21
bob        23
chrlic     22
dennies    34
dtype: int64
23
Index(['alice', 'bob', 'chrlic', 'dennies'], dtype='str')

In [23]:
#dataframe
info ={
    "name" : ["aayu" , "shipi" , "anj" , "kb"],
    "cgpa" : [9.5 , 7.5 , 5.6 ,7.8],
    "age" : [21, 22,23,25]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

    name  cgpa  age
0   aayu   9.5   21
1  shipi   7.5   22
2    anj   5.6   23
3     kb   7.8   25
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'cgpa', 'age'], dtype='str')

In [18]:
df

    name  cgpa  age
0   aayu   9.5   21
1  shipi   7.5   22
2    anj   5.6   23
3     kb   7.8   25

In [25]:
df = pd.DataFrame([["aayu" ,21], ["shipi" ,22] , ["anj" , 23] , ["kb" ,25]] , columns=["name" , "age"])
print(df)

    name  age
0   aayu   21
1  shipi   22
2    anj   23
3     kb   25

In [26]:
import numpy as np

np_arr = np.array([[1,2,3] , [4,5,6]])
df = pd.DataFrame(np_arr , columns =["A" ,"B" , "C"])
print(df)

AttributeError: module 'pandas' has no attribute 'DartaFrame'